name: 'Contributors To File'
description: "Write your repo's contributor list to a file"
inputs:
  file_in_repo:
    description: 'The location of the file in the repository to write to'
    required: true
outputs:
  status:
    description: 'If the file has changed'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file_in_repo }}
